### ISSUE TITLE
Feature Request: Years and Months

### ISSUE THREAD

**Issue by cesar-programs** [xxchan/logseq-deadline-countdown#5]
A nice toggle feature in settings would be to have the ability to render countdowns with a certain number of days to their month or year equivalent. 

For example, if our date is two years in advance, instead of having 730d, we would have 2y indicated in the render. This transformation from days to years and months may be visually helpful when things are scheduled further in advance. 

Thank you.

**Comment by xxchan** [comment]
Hi, thanks for your feature request. But this plugin is intended to be minimal. For advanced features, you can take a look at https://github.com/KerfuffleV2/logseq-plugin-interval-hints (maybe send a feature request there)

**Comment by cesar-programs** [comment]
Thanks for the referral, @xxchan
