### ISSUE TITLE
Minimum Interval set to "days" calculates interval based on hours instead of days

### ISSUE THREAD

**Issue by snezhniylis** [xxchan/logseq-deadline-countdown#6]
When "Minimum Interval" option is set to "days", the interval is calculated by taking the difference between current and target hours and rounding it down to days.

The optimal behavior (in my case) would be to calculate the difference between the days in the date:
![image](https://user-images.githubusercontent.com/85341530/187040477-03e16e17-5c15-4efb-82ae-06df5c41ac39.png)

I use this plugin heavily to estimate my deadlines and TODOs and having to add +1d to almost every ETA I encounter is distracting and mentally taxing.

If the current behavior is expected behavior, would there be a possibility to add an option for calculating actual days between dates?

**Comment by xxchan** [comment]
Hi, thanks for your question, and I think it mases sense. It seems this behavior is changed after #3. I will have a fix soon.

**Comment by xxchan** [comment]
Should be fixed in 0.0.7. Please tell me if there's still any problems :)

**Comment by snezhniylis** [comment]
Thank you so much for responding and fixing this so quickly! Now it works just as one would expect. The only odd thing that caught my eye is getting `(past 0d)` for timestamps with current date. Other than that, it's perfect:
![image](https://user-images.githubusercontent.com/85341530/187092473-0dbd55ac-a375-41a5-9089-46edbe4edc48.png)

**Comment by xxchan** [comment]
I just updated `past 0d` to `today` 😄

**Comment by snezhniylis** [comment]
Now it's perfect. Thank you!
