### ISSUE TITLE
Trouble installing on Version 0.9.10

### ISSUE THREAD

**Issue by bridgestew** [xxchan/logseq-deadline-countdown#7]
Developer mode is turned on and Logseq had been restarted when attempting to install.

This is the error message on first attempt:

[Error]<logseq-deadline-countdown> :end of central directory record signature not found

After closing that message and clicking install again, this error message appears:
[Main Exception]
ENOENT: no such file or directory, rename '/var/folders/yq/1hcpn6bs3tb17hl2x2kbkj880000gn/T/logseq-deadline-countdown-0.0.8.zip.pending' -> '/var/folders/yq/1hcpn6bs3tb17hl2x2kbkj880000gn/T/logseq-deadline-countdown-0.0.8.zip'
Error: ENOENT: no such file or directory, rename '/var/folders/yq/1hcpn6bs3tb17hl2x2kbkj880000gn/T/logseq-deadline-countdown-0.0.8.zip.pending' -> '/var/folders/yq/1hcpn6bs3tb17hl2x2kbkj880000gn/T/logseq-deadline-countdown-0.0.8.zip'
at Object.renameSync (node:fs:993:3)
at PassThrough.<anonymous> (/Applications/Logseq.app/Contents/Resources/app/electron.js:14252:48)
at PassThrough.emit (node:events:527:28)
at endReadableNT (node:internal/streams/readable:1345:12)
at process.processTicksAndRejections (node:internal/process/task_queues:83:21)

Other plugins I have installed, in case this helps in troubleshooting:
Todo List
Get Webpage Title
Logseq Jira Sync
Awesome Links
Automatic Linker
Table Picker

**Comment by xxchan** [comment]
Did you try to install again? This looks like a temporary network issue to me.
